### ISSUE TITLE
 AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'

### ISSUE THREAD

**Issue by julandalf** [hakyimlab/PrediXcan#32] opened 2018-05-03 13:30 UTC
./PrediXcan.py --predict --assoc --linear \
               --weights weights/Brain_Frontal_Cortex_BA9/gtex_v7_Brain_Frontal_Cortex_BA9_imputed_europeans_tw_0.5_signif.db \
               --dosages genotype/ \
               --dosages_prefix "chr22.dosage.txt.gz" \
               --samples genotype/chr22.txt \
               --pheno phenotype/phenotype.txt \
               --output_prefix results/chr22 

2018-05-03 15:28:56.746566 Preloading weights...
2018-05-03 15:28:56.970715 Processing chr22.dosage.txt.gz
Traceback (most recent call last):
  File "./PrediXcan.py", line 230, in <module>
    main()
  File "./PrediXcan.py", line 212, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "./PrediXcan.py", line 117, in save
    outfile.write('FID\t' + 'IID\t' + '\t'.join(self.gene_list) + '\n') # Nb. this lists the names of rows, not of columns

AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'

**Comment by rbonazzola** [comment] 2018-05-03 16:32
Hello julandalf,

Could you please confirm that your dosage file complies with the format:
`chromosome rsid position allele1 allele2 MAF id1 ..... idn`?
Notice that the second column must contain rsid's for the SNPs (and not other kind of ID's, like `chr:position`). This is important because this is the way the SNPs in your dosage files are matched with the SNPs in the prediction models.

If all of this looks good, I will ask you some other questions to figure out what the problem is.

Thanks,
Rodrigo

**Comment by rbonazzola** [comment] 2018-05-10 06:06
Hello,

Could you solve your problem? If so, I would like to close this issue.

Thanks,
Rodrigo

**Comment by Heroico** [comment] 2019-02-01 15:07
Closing for lack of activity.

**Closed as completed by Heroico** 2019-02-01 15:07 UTC
